language: minimal
dist: focal

before_install:
  - sudo unlink /usr/local/bin/packer
  - ci/provision.sh

script:
- sudo make dist

before_deploy:
- cd dist && sudo ../ci/hashgen.sh && cd ..

deploy:
  provider: releases
  api_key:
    secure: 1aPl381dJEmlPqVdFVofm27aUfPYy5JkXUc2gObWJeceMPCORBNdJmnequpted35kTAwGGoN6109i3V4p62+9GUMwOua0/GO5NUEWr5sYIbFLqsHLxS3HM7fhrl+XzcaPlfgGhNyunnqT3OT/KRXL1Gn538r30tdRo+DN0y2zGJFFSxHHrNOOCpHyVwGlugC1uCwUVN+Fs/EjF1ZBEvalrSansZSZp8a6ejC8AZnf726IToCAMwCocqhkDme+DGNpV3qBAbYIJP6H4wlp0B9ZV07FjuTgfEUDQg7RBb60zRb+tbTRhtFg62LjpS6T+xZTNnBuG4BBO4kwUn2TagkNByy9GRiEnXbKx/RweNQP008m06FXdbC5SmAiZPf4a1jVUtg78RTdIhM4fb47jFnufknBSUyR7VHZj3qgVYF3T2M4dys4OcOL2cr/Bl02SIASMQOY0bD6YesfqEZtWkaIBpcVMnrsmkKyqSGjF0FRap0zoSQVW81LF2PVEJcXiICyAvEIQIEM1/nRK0A8s89Hk8uDQgSSrVih5tK0PbWbqsr747/Qdi3qf9i9QRZculRGY1LoS0800iV5DebSVG+0RTwJcoAiAGq/ElakYE+QKR051VeOGBLno3tCGxMsjWMJ0qN/tmvjoHRpY+yrEtrlzd25QGU4IxAkRuPy05DIeI=
  file_glob: true
  file: 
    - dist/*.zip
    - dist/*.zip.sha256
  skip_cleanup: true
  on:
    tags: true