language: minimal

services:
- docker

before_install:
- docker pull quay.io/solo-io/packer-builder-arm-image:v0.1.4.5

script:
- sudo make k3s-agent
- sudo tar -czvf dist/rpi-k3s-agent.tgz -C dist rpi-k3s-agent.iso
- sudo make k3s-server
- sudo tar -czvf dist/rpi-k3s-server.tgz -C dist rpi-k3s-server.iso